### ISSUE TITLE
Setting User Code (You are not authorized to perform the requested operation)

### ISSUE THREAD

**Issue by cwdsmith** [ethayer/user-lock-manager#14]
When I click on user settings and then any of the user positions to set the code I get the following message "You are not authorized to perform the requested operation"

SmartThings Debug output is as follows:
3f56397a-5bcf-43dd-89de-257b92bb7180 ‎4‎:‎32‎:‎53‎ ‎PM: error java.lang.NullPointerException: Cannot invoke method isNumber() on null object @ line 259

I am using
Smartthings Controller
Windows Phone
Schlage FE599NX

**Comment by ethayer** [comment]
Seems like Windows phone SmartThings platform is not supported at this time.  I'll install the SDK and see if I can't work out the bug.. but the bug probably is in ST's court to fix.

**Comment by vernondraper** [comment]
I'm having the same message when setting a user code with a Schlage.  It worked well on my STv1 Hub and was a favorite.  I am trying to set it up again on my new STv2 Hub.

I have tried this on the ST2.0 app on Android and the ST1.0 app on iOS with this same error from Live Logging.  The error happens each time I click  to set a user code.

I hope this helps.

6760e565-dfc8-4ef5-b45b-59a358c47d2c 9:50:27 PM: error groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method physicalgraph.app.InstalledSmartAppService#executeAction.
Cannot resolve which method to invoke for [null, class java.lang.String, interface java.util.List] due to overlapping prototypes between:
[class physicalgraph.app.InstalledSmartApp, class java.lang.String, class java.lang.Object]
[class physicalgraph.device.cache.InstalledSmartAppDTO, class java.lang.String, class java.lang.Object] @ line 125

-Vernon

**Comment by ethayer** [comment]
Closing for now, as I think this issue has been fixed.  Let me know if you still see this as an issue.

**Comment by trippy99** [comment]
Hey @ethayer have you heard of any bug that drains battery life? My Yale smartlock ran down super fast recently, since I upgraded to 4.1.1.
